"""Approved bilingual FAQ corpus for the ChainReporter chatbot."""


# key, priority, English keywords, Persian keywords, English Q/A, Persian Q/A
_PAIRS = (
    ('website_overview', 50, ('chainreporter website', 'website overview', 'workspace'), ('وب سایت chainreporter', 'معرفی سایت', 'محیط کار'),
     'What is the ChainReporter website?', 'ChainReporter is a multi-brand workspace for finding news, routing stories, and preparing social-media copy and images.',
     'وب‌سایت ChainReporter چیست؟', 'ChainReporter یک محیط چندرسانه‌ای برای یافتن خبر، مسیردهی داستان‌ها و آماده‌سازی متن و تصویر شبکه‌های اجتماعی است.'),
    ('available_brands', 70, ('media brands', 'available brands', 'supported brands'), ('برندهای رسانه ای', 'برندهای موجود', 'رسانه ها'),
     'Which media brands are available?', 'The available media brands are RZ Prime, Coin Hall, Meta Coin Guard, and ChainReporter.',
     'چه برندهای رسانه‌ای در دسترس هستند؟', 'برندهای رسانه‌ای موجود شامل RZ Prime، Coin Hall، Meta Coin Guard و ChainReporter هستند.'),
    ('rz_prime', 90, ('rz prime', 'token reservation', 'reserve token'), ('rz prime', 'رزرو توکن', 'فرصت توکن'),
     'What is RZ Prime?', 'RZ Prime is a token-reservation platform where users can reserve token opportunities without an upfront payment and manage the process through smart contracts.',
     'RZ Prime چیست؟', 'RZ Prime یک پلتفرم رزرو توکن است که کاربران می‌توانند بدون پرداخت اولیه فرصت‌های توکن را رزرو و فرایند را از طریق قراردادهای هوشمند مدیریت کنند.'),
    ('coin_hall', 90, ('coin hall', 'real world asset', 'rwa'), ('coin hall', 'دارایی واقعی', 'دارایی توکنیزه'),
     'What is Coin Hall?', 'Coin Hall presents time-limited opportunities involving tokenized real-world assets such as jewelry, real estate, and cars.',
     'Coin Hall چیست؟', 'Coin Hall فرصت‌های زمان‌دار مربوط به دارایی‌های واقعی توکنیزه‌شده مانند جواهرات، املاک و خودرو را ارائه می‌کند.'),
    ('meta_coin_guard', 90, ('meta coin guard', 'token protection', 'crypto protection'), ('meta coin guard', 'محافظت توکن', 'امنیت رمزارز'),
     'What is Meta Coin Guard?', 'Meta Coin Guard is a non-custodial, smart-contract-based service designed to protect crypto token value through documented cover plans.',
     'Meta Coin Guard چیست؟', 'Meta Coin Guard یک سرویس غیرامانی مبتنی بر قرارداد هوشمند است که برای حفاظت از ارزش توکن‌های رمزارزی از طریق طرح‌های پوشش مستند طراحی شده است.'),
    ('chainreporter_media', 90, ('chainreporter cover', 'chainreporter news', 'crypto news outlet'), ('پوشش chainreporter', 'اخبار chainreporter', 'رسانه رمزارز'),
     'What does ChainReporter cover?', 'ChainReporter covers crypto markets, regulation, security incidents, exchanges, launches, governance, protocols, and important industry participants.',
     'ChainReporter چه موضوعاتی را پوشش می‌دهد؟', 'ChainReporter بازار رمزارز، مقررات، رویدادهای امنیتی، صرافی‌ها، راه‌اندازی‌ها، حاکمیت، پروتکل‌ها و افراد مهم صنعت را پوشش می‌دهد.'),
    ('security_brand', 80, ('security news brand', 'hack exploit brand', 'crypto security story'), ('برند خبر امنیتی', 'هک و حمله', 'خبر امنیت رمزارز'),
     'Which brand should cover crypto-security news?', 'Meta Coin Guard is the primary fit for security, exploit, wallet-risk, scam, and smart-contract-risk stories.',
     'کدام برند باید اخبار امنیت رمزارز را پوشش دهد؟', 'Meta Coin Guard انتخاب اصلی برای اخبار امنیتی، حملات، ریسک کیف پول، کلاهبرداری و ریسک قرارداد هوشمند است.'),
    ('general_news_brand', 80, ('general crypto news brand', 'market regulation brand', 'mainstream crypto'), ('برند اخبار عمومی رمزارز', 'بازار و مقررات', 'اخبار عمومی'),
     'Which brand should cover general crypto news?', 'ChainReporter is the primary fit for broad crypto, market, regulation, exchange, ETF, and institutional stories.',
     'کدام برند باید اخبار عمومی رمزارز را پوشش دهد؟', 'ChainReporter انتخاب اصلی برای اخبار گسترده رمزارز، بازار، مقررات، صرافی، ETF و فعالیت‌های سازمانی است.'),
    ('reservation_brand', 80, ('token reservation brand', 'token deal brand', 'zero upfront'), ('برند رزرو توکن', 'فرصت توکن', 'بدون پیش پرداخت'),
     'Which brand fits token-reservation stories?', 'RZ Prime is the primary fit for token-reservation opportunities and related smart-contract processes.',
     'کدام برند برای اخبار رزرو توکن مناسب است؟', 'RZ Prime انتخاب اصلی برای فرصت‌های رزرو توکن و فرایندهای مرتبط با قرارداد هوشمند است.'),
    ('rwa_brand', 80, ('rwa brand', 'tokenized asset brand', 'jewelry property cars'), ('برند دارایی واقعی', 'دارایی توکنیزه', 'جواهرات املاک خودرو'),
     'Which brand fits tokenized real-world-asset stories?', 'Coin Hall is the primary fit for tokenized real-world assets, luxury assets, property, jewelry, and cars.',
     'کدام برند برای اخبار دارایی واقعی توکنیزه‌شده مناسب است؟', 'Coin Hall انتخاب اصلی برای دارایی‌های واقعی توکنیزه‌شده، دارایی‌های لوکس، املاک، جواهرات و خودرو است.'),
    ('select_brand', 60, ('select media brand', 'choose brand', 'why select media'), ('انتخاب برند رسانه ای', 'چرا برند انتخاب کنم', 'انتخاب رسانه'),
     'Why should I select a media brand?', 'Selecting a media brand tells the editorial pipeline which brand documents, audience, tone, and routing rules should guide the result.',
     'چرا باید یک برند رسانه‌ای انتخاب کنم؟', 'انتخاب برند رسانه‌ای مشخص می‌کند کدام اسناد برند، مخاطب، لحن و قوانین مسیردهی نتیجه را هدایت کنند.'),
    ('multiple_brands', 60, ('multiple media brands', 'select several brands', 'more than one brand'), ('چند برند رسانه ای', 'انتخاب چند برند', 'بیش از یک برند'),
     'Can I select multiple media brands?', 'Yes. The pipeline can evaluate stories for multiple selected brands and route each story to the strongest fit.',
     'آیا می‌توانم چند برند رسانه‌ای انتخاب کنم؟', 'بله. سیستم می‌تواند خبرها را برای چند برند انتخاب‌شده بررسی و هر خبر را به مناسب‌ترین برند هدایت کند.'),
    ('analyze_button', 70, ('analyze button', 'analyze stories', 'run analysis'), ('دکمه analyze', 'تحلیل خبر', 'اجرای تحلیل'),
     'How does the Analyze button work?', 'Analyze collects the selected stories and settings, filters the stories, scores their editorial fit, and routes suitable stories into brand lanes.',
     'دکمه Analyze چگونه کار می‌کند؟', 'Analyze خبرها و تنظیمات انتخاب‌شده را جمع‌آوری، خبرها را فیلتر، تناسب تحریریه را امتیازدهی و خبرهای مناسب را به مسیر برندها هدایت می‌کند.'),
    ('news_sources', 60, ('news sources', 'source selection', 'available sources'), ('منابع خبر', 'انتخاب منبع', 'منابع موجود'),
     'What news sources can I use?', 'You can use configured RSS sources and selected public Telegram channels from the Multimedia sidebar.',
     'از چه منابع خبری می‌توانم استفاده کنم؟', 'می‌توانید از منابع RSS پیکربندی‌شده و کانال‌های عمومی تلگرام انتخاب‌شده در نوار کناری Multimedia استفاده کنید.'),
    ('rss_sources', 70, ('rss source', 'rss feed', 'import feed'), ('منبع rss', 'فید rss', 'ورود فید'),
     'How do RSS sources work?', 'Select or enter an RSS source, configure the analysis settings, and run Analyze to evaluate recent articles from that feed.',
     'منابع RSS چگونه کار می‌کنند؟', 'یک منبع RSS را انتخاب یا وارد کنید، تنظیمات تحلیل را مشخص و Analyze را اجرا کنید تا مقاله‌های اخیر آن فید بررسی شوند.'),
    ('telegram_sources', 70, ('telegram sources', 'telegram channels', 'public telegram'), ('منابع تلگرام', 'کانال تلگرام', 'تلگرام عمومی'),
     'How do Telegram sources work?', 'Select public Telegram channels in the sidebar, choose the desired time range and sorting settings, and run Analyze.',
     'منابع تلگرام چگونه کار می‌کنند؟', 'کانال‌های عمومی تلگرام را در نوار کناری انتخاب کنید، بازه زمانی و تنظیمات مرتب‌سازی را مشخص و Analyze را اجرا کنید.'),
    ('source_tooltip', 70, ('source tooltip', 'source information', 'source icon'), ('توضیح منبع', 'اطلاعات منبع', 'آیکون منبع'),
     'How can I learn what a Telegram source covers?', 'Hover over a Telegram source and wait briefly to see its description and visual category information.',
     'چگونه بفهمم یک منبع تلگرام چه موضوعاتی را پوشش می‌دهد؟', 'نشانگر را روی منبع تلگرام نگه دارید و کمی صبر کنید تا توضیح و اطلاعات تصویری دسته‌بندی آن نمایش داده شود.'),
    ('platforms', 70, ('supported platforms', 'content platforms', 'telegram x instagram'), ('پلتفرم های پشتیبانی شده', 'پلتفرم محتوا', 'تلگرام x اینستاگرام'),
     'Which content platforms are supported?', 'ChainReporter can prepare content for Telegram, X, and Instagram. Direct publishing is currently limited to Telegram and X.',
     'چه پلتفرم‌هایی برای محتوا پشتیبانی می‌شوند؟', 'ChainReporter می‌تواند برای تلگرام، X و اینستاگرام محتوا آماده کند. انتشار مستقیم در حال حاضر به تلگرام و X محدود است.'),
    ('editorial_models', 60, ('editorial models', 'ai models', 'select model'), ('مدل تحریریه', 'مدل هوش مصنوعی', 'انتخاب مدل'),
     'What are editorial models?', 'Editorial models evaluate, select, and prepare stories. You can choose the available models before running an analysis.',
     'مدل‌های تحریریه چه هستند؟', 'مدل‌های تحریریه خبرها را ارزیابی، انتخاب و آماده می‌کنند. می‌توانید پیش از اجرای تحلیل، مدل‌های موجود را انتخاب کنید.'),
    ('story_routing', 60, ('story routing', 'route to brands', 'filter scoring'), ('مسیردهی خبر', 'هدایت به برند', 'فیلتر و امتیاز'),
     'How are stories routed to brands?', 'The editorial pipeline evaluates topic relevance, brand fit, freshness, source quality, and selected settings before assigning stories.',
     'خبرها چگونه به برندها مسیردهی می‌شوند؟', 'سیستم تحریریه ارتباط موضوعی، تناسب برند، تازگی، کیفیت منبع و تنظیمات انتخاب‌شده را پیش از تخصیص خبر بررسی می‌کند.'),
    ('brand_lanes', 60, ('brand lanes', 'card lanes', 'lane board'), ('مسیر برند', 'ستون کارت', 'برد مسیر'),
     'What are brand lanes?', 'Brand lanes organize analyzed news cards by their assigned media brand and content platform.',
     'مسیرهای برند چه هستند؟', 'مسیرهای برند، کارت‌های خبری تحلیل‌شده را بر اساس برند رسانه‌ای و پلتفرم محتوایی مرتب می‌کنند.'),
    ('open_card', 60, ('open news card', 'card preview', 'click card'), ('باز کردن کارت خبر', 'پیش نمایش کارت', 'کلیک کارت'),
     'What happens when I open a news card?', 'The Preview panel opens with the card’s headline, copy, platform, brand, image controls, and available actions.',
     'وقتی یک کارت خبر را باز می‌کنم چه اتفاقی می‌افتد؟', 'پنل Preview همراه با تیتر، متن، پلتفرم، برند، کنترل‌های تصویر و عملیات موجود کارت باز می‌شود.'),
    ('generate_copy', 70, ('generate social copy', 'create caption', 'copy generation'), ('تولید متن شبکه اجتماعی', 'ساخت کپشن', 'تولید متن'),
     'How do I generate social-media copy?', 'Open a routed card, select its destination platform, and use the copy-generation control to create platform-specific text.',
     'چگونه متن شبکه اجتماعی تولید کنم؟', 'یک کارت مسیردهی‌شده را باز، پلتفرم مقصد را انتخاب و از کنترل تولید متن برای ساخت متن مخصوص همان پلتفرم استفاده کنید.'),
    ('platform_copy', 70, ('platform specific copy', 'different platform copy', 'telegram x copy'), ('متن مخصوص پلتفرم', 'متن متفاوت پلتفرم', 'متن تلگرام و x'),
     'Is generated copy different for each platform?', 'Yes. The copy generator applies the formatting, length, hashtag, and style requirements of the selected platform.',
     'آیا متن تولیدشده برای هر پلتفرم متفاوت است؟', 'بله. تولیدکننده متن، قالب، طول، هشتگ و الزامات سبک پلتفرم انتخاب‌شده را اعمال می‌کند.'),
    ('copy_variants', 60, ('copy variants', 'alternative copy', 'another caption'), ('نسخه متن', 'متن جایگزین', 'کپشن دیگر'),
     'Can I generate alternative copy variants?', 'Yes. The copy workflow can provide alternative versions that you can review and edit before saving or publishing.',
     'آیا می‌توانم نسخه‌های جایگزین متن تولید کنم؟', 'بله. فرایند تولید متن می‌تواند نسخه‌های جایگزین ارائه کند تا پیش از ذخیره یا انتشار آن‌ها را بررسی و ویرایش کنید.'),
    ('hashtags', 60, ('hashtags', 'brand hashtag', 'select hashtags'), ('هشتگ', 'هشتگ برند', 'انتخاب هشتگ'),
     'How are hashtags selected?', 'Hashtags are generated from the article topic and platform context, and the appropriate brand-identity hashtag is preserved.',
     'هشتگ‌ها چگونه انتخاب می‌شوند؟', 'هشتگ‌ها بر اساس موضوع مقاله و شرایط پلتفرم تولید می‌شوند و هشتگ هویتی مناسب برند حفظ می‌شود.'),
    ('edit_copy', 60, ('edit copy', 'edit headline', 'change caption'), ('ویرایش متن', 'ویرایش تیتر', 'تغییر کپشن'),
     'Can I edit generated copy and headlines?', 'Yes. Use the Preview panel to edit the visible copy or headline before saving, scheduling, or publishing.',
     'آیا می‌توانم متن و تیتر تولیدشده را ویرایش کنم؟', 'بله. از پنل Preview برای ویرایش متن یا تیتر پیش از ذخیره، زمان‌بندی یا انتشار استفاده کنید.'),
    ('generate_image', 70, ('generate image', 'news image', 'create visual'), ('تولید تصویر', 'تصویر خبر', 'ساخت تصویر'),
     'How do I generate an image?', 'Open a news card in Preview and use the image-generation control. The website uses the selected story and brand guidance to create the image.',
     'چگونه یک تصویر تولید کنم؟', 'کارت خبر را در Preview باز و از کنترل تولید تصویر استفاده کنید. وب‌سایت از خبر انتخاب‌شده و راهنمای برند برای ساخت تصویر استفاده می‌کند.'),
    ('image_art_director', 70, ('image art director', 'art direction', 'image brief'), ('کارگردان هنری تصویر', 'هدایت هنری', 'بریف تصویر'),
     'What does the image Art Director do?', 'The Art Director converts article facts and brand guidance into a validated visual brief and a structured image-generation prompt.',
     'کارگردان هنری تصویر چه کاری انجام می‌دهد؟', 'کارگردان هنری، اطلاعات مقاله و راهنمای برند را به یک بریف تصویری تاییدشده و پرامپت ساختاریافته تولید تصویر تبدیل می‌کند.'),
    ('regenerate_image', 60, ('regenerate image', 'new image', 'another image'), ('بازتولید تصویر', 'تصویر جدید', 'تصویر دیگر'),
     'Can I regenerate an image?', 'Yes. You can request another image from the card Preview when the current result is unsuitable.',
     'آیا می‌توانم تصویر را دوباره تولید کنم؟', 'بله. اگر نتیجه فعلی مناسب نیست، می‌توانید از Preview کارت تصویر دیگری درخواست کنید.'),
    ('preview_panel', 60, ('preview panel', 'card preview', 'what is preview'), ('پنل preview', 'پیش نمایش کارت', 'preview چیست'),
     'What is the Preview panel?', 'Preview is the card workspace for reviewing and editing copy, creating images, saving, scheduling, and publishing supported content.',
     'پنل Preview چیست؟', 'Preview محیط کارت برای بررسی و ویرایش متن، ساخت تصویر، ذخیره، زمان‌بندی و انتشار محتوای پشتیبانی‌شده است.'),
    ('save_card', 70, ('save news card', 'save content', 'save for later'), ('ذخیره کارت خبر', 'ذخیره محتوا', 'ذخیره برای بعد'),
     'How do I save a news card?', 'Open the card Preview and select Save. The saved card will become available from the Account page.',
     'چگونه یک کارت خبر را ذخیره کنم؟', 'Preview کارت را باز و Save را انتخاب کنید. کارت ذخیره‌شده در صفحه Account در دسترس خواهد بود.'),
    ('saved_cards', 70, ('find saved cards', 'saved content', 'where saved'), ('کارت های ذخیره شده', 'محتوای ذخیره شده', 'محل ذخیره'),
     'Where can I find saved cards?', 'Saved cards are listed on the Account page, where they can be reviewed, updated, scheduled, or discarded.',
     'کارت‌های ذخیره‌شده را کجا پیدا کنم؟', 'کارت‌های ذخیره‌شده در صفحه Account فهرست می‌شوند و می‌توانید آن‌ها را بررسی، ویرایش، زمان‌بندی یا حذف کنید.'),
    ('schedule_content', 70, ('schedule content', 'schedule post', 'date and time'), ('زمان بندی محتوا', 'زمان بندی پست', 'تاریخ و ساعت'),
     'How do I schedule content?', 'Open Preview, select Schedule, and choose the required date and time.',
     'چگونه محتوا را زمان‌بندی کنم؟', 'Preview را باز، Schedule را انتخاب و تاریخ و ساعت موردنظر را مشخص کنید.'),
    ('manage_schedule', 70, ('manage scheduled content', 'reschedule', 'cancel schedule'), ('مدیریت محتوای زمان بندی شده', 'تغییر زمان', 'لغو زمان بندی'),
     'Can I manage scheduled content?', 'Yes. The Account page allows you to review scheduled content and use the available cancel or reschedule controls.',
     'آیا می‌توانم محتوای زمان‌بندی‌شده را مدیریت کنم؟', 'بله. صفحه Account امکان بررسی محتوای زمان‌بندی‌شده و استفاده از کنترل‌های لغو یا تغییر زمان را فراهم می‌کند.'),
    ('publish_telegram', 80, ('publish telegram', 'send to telegram', 'telegram post'), ('انتشار تلگرام', 'ارسال به تلگرام', 'پست تلگرام'),
     'Can ChainReporter publish directly to Telegram?', 'Yes. Supported Telegram content can be published through the Telegram action in Preview when the channel is configured.',
     'آیا ChainReporter می‌تواند مستقیماً در تلگرام منتشر کند؟', 'بله. اگر کانال پیکربندی شده باشد، محتوای پشتیبانی‌شده از طریق عملیات تلگرام در Preview منتشر می‌شود.'),
    ('publish_x', 80, ('publish x', 'twitter post', 'send to x'), ('انتشار در x', 'پست توییتر', 'ارسال به x'),
     'Can ChainReporter publish directly to X?', 'Yes. Supported content can be published to the configured X account through Preview.',
     'آیا ChainReporter می‌تواند مستقیماً در X منتشر کند؟', 'بله. محتوای پشتیبانی‌شده از طریق Preview در حساب پیکربندی‌شده X منتشر می‌شود.'),
    ('instagram_content', 80, ('instagram content', 'instagram caption', 'instagram visual'), ('محتوای اینستاگرام', 'کپشن اینستاگرام', 'تصویر اینستاگرام'),
     'Can ChainReporter prepare Instagram content?', 'Yes. ChainReporter can generate and edit Instagram-oriented copy and visual content.',
     'آیا ChainReporter می‌تواند محتوای اینستاگرام آماده کند؟', 'بله. ChainReporter می‌تواند متن و محتوای تصویری مناسب اینستاگرام را تولید و ویرایش کند.'),
    ('publish_instagram', 100, ('publish directly instagram', 'post to instagram', 'instagram publishing'), ('انتشار مستقیم اینستاگرام', 'ارسال به اینستاگرام', 'انتشار اینستاگرام'),
     'Can ChainReporter publish directly to Instagram?', 'No. ChainReporter can prepare Instagram content, but direct Instagram publishing is not currently available.',
     'آیا ChainReporter می‌تواند مستقیماً در اینستاگرام منتشر کند؟', 'خیر. ChainReporter می‌تواند محتوای اینستاگرام را آماده کند، اما انتشار مستقیم در اینستاگرام در حال حاضر در دسترس نیست.'),
    ('translate_cards', 70, ('translate news cards', 'card translation', 'translate content'), ('ترجمه کارت خبر', 'ترجمه کارت', 'ترجمه محتوا'),
     'Can ChainReporter translate news cards?', 'Yes. Use the translation control on the selected cards and choose English or Persian as the target language.',
     'آیا ChainReporter می‌تواند کارت‌های خبری را ترجمه کند؟', 'بله. از کنترل ترجمه روی کارت‌های انتخاب‌شده استفاده و انگلیسی یا فارسی را به‌عنوان زبان مقصد انتخاب کنید.'),
    ('languages', 90, ('supported languages', 'english persian', 'website language'), ('زبان های پشتیبانی شده', 'انگلیسی فارسی', 'زبان وب سایت'),
     'Which website languages are supported?', 'The supported website and chatbot languages are English and Persian only.',
     'چه زبان‌هایی در وب‌سایت پشتیبانی می‌شوند؟', 'زبان‌های پشتیبانی‌شده وب‌سایت و چت‌بات فقط انگلیسی و فارسی هستند.'),
    ('login_language', 90, ('login language', 'persian login', 'english login page'), ('زبان ورود', 'لاگین فارسی', 'صفحه ورود انگلیسی'),
     'Can the login page be displayed in Persian?', 'No. The login page always remains in English, even when Persian is selected elsewhere on the website.',
     'آیا صفحه ورود می‌تواند فارسی نمایش داده شود؟', 'خیر. صفحه ورود همیشه انگلیسی باقی می‌ماند، حتی اگر در بخش‌های دیگر وب‌سایت فارسی انتخاب شده باشد.'),
    ('account_page', 60, ('account page', 'account information', 'account statistics'), ('صفحه account', 'اطلاعات حساب', 'آمار حساب'),
     'What information is available on the Account page?', 'Account shows activity statistics, posts by brand, recent keywords, saved cards, and scheduled content.',
     'چه اطلاعاتی در صفحه Account وجود دارد؟', 'Account آمار فعالیت، پست‌ها بر اساس برند، کلمات کلیدی اخیر، کارت‌های ذخیره‌شده و محتوای زمان‌بندی‌شده را نمایش می‌دهد.'),
    ('google_sheets', 70, ('google sheets', 'sync sheet', 'apps script'), ('گوگل شیت', 'همگام سازی شیت', 'apps script'),
     'Can approved content be synchronized with Google Sheets?', 'Yes. Supported approval and scheduling workflows can send their information through the configured Google Apps Script integration.',
     'آیا محتوای تاییدشده با Google Sheets همگام می‌شود؟', 'بله. فرایندهای پشتیبانی‌شده تایید و زمان‌بندی می‌توانند اطلاعات را از طریق اتصال پیکربندی‌شده Google Apps Script ارسال کنند.'),
    ('chatbot_scope', 80, ('chatbot help', 'assistant scope', 'what can chatbot do'), ('کمک چت بات', 'محدوده دستیار', 'چت بات چه کاری می کند'),
     'What can the chatbot help me with?', 'The chatbot answers questions about the four media brands, active news cards, and documented ChainReporter functions.',
     'چت‌بات در چه مواردی می‌تواند کمک کند؟', 'چت‌بات درباره چهار برند رسانه‌ای، کارت خبر فعال و قابلیت‌های مستند ChainReporter پاسخ می‌دهد.'),
    ('selected_media_context', 70, ('chatbot selected media', 'selected brands context', 'know selected brand'), ('رسانه انتخاب شده چت بات', 'زمینه برند انتخاب شده', 'تشخیص برند انتخاب شده'),
     'Does the chatbot know which media brands I selected?', 'Yes. The current media selection is sent as context with your question, allowing the chatbot to focus on one brand or ask which selected brand you mean.',
     'آیا چت‌بات می‌داند کدام برندهای رسانه‌ای را انتخاب کرده‌ام؟', 'بله. انتخاب فعلی رسانه همراه پرسش ارسال می‌شود تا چت‌بات روی یک برند تمرکز کند یا بپرسد منظور شما کدام برند انتخاب‌شده است.'),
    ('active_card_context', 70, ('chatbot active card', 'open card context', 'understand current card'), ('کارت فعال چت بات', 'زمینه کارت باز', 'درک کارت فعلی'),
     'Does the chatbot understand the open news card?', 'Yes. When a card is open, its brand, platform, headline, and available copy are provided as temporary context for your question.',
     'آیا چت‌بات کارت خبر بازشده را درک می‌کند؟', 'بله. وقتی کارتی باز است، برند، پلتفرم، تیتر و متن موجود آن به‌عنوان زمینه موقت پرسش در اختیار چت‌بات قرار می‌گیرد.'),
    ('chat_history', 80, ('chat history', 'one hour chat', 'delete messages', 'clear chat'), ('تاریخچه چت', 'یک ساعت چت', 'حذف پیام', 'پاک کردن چت'),
     'How long are chat messages stored?', 'Chat messages are deleted after one hour without a new message. You can also clear the conversation manually.',
     'پیام‌های چت چه مدت نگهداری می‌شوند؟', 'پیام‌های چت پس از یک ساعت نبود پیام جدید حذف می‌شوند. همچنین می‌توانید گفتگو را به‌صورت دستی پاک کنید.'),
    ('zero_token_answers', 80, ('zero token answer', 'permanent cache', 'faq cache', 'without ai tokens'), ('پاسخ بدون توکن', 'حافظه دائمی', 'کش faq', 'بدون توکن هوش مصنوعی'),
     'How does the chatbot answer without using AI tokens?', 'It checks local policy responses, approved FAQs, and the permanent brand-and-language-aware answer cache before calling OpenRouter.',
     'چت‌بات چگونه بدون مصرف توکن هوش مصنوعی پاسخ می‌دهد؟', 'پیش از فراخوانی OpenRouter، پاسخ‌های قوانین محلی، FAQ تاییدشده و حافظه دائمی حساس به برند و زبان بررسی می‌شوند.'),
    ('unsupported_actions', 100, ('website cannot do', 'unsupported action', 'email delivery', 'linkedin publishing', 'crypto trading', 'wallet transaction', 'video generation'), ('کارهای پشتیبانی نشده', 'وب سایت نمی تواند', 'ارسال ایمیل', 'انتشار لینکدین', 'معامله رمزارز', 'تراکنش کیف پول', 'تولید ویدیو'),
     'What can the website not do?', 'The website cannot perform undocumented actions such as email delivery, LinkedIn publishing, crypto trading, payments, wallet transactions, external web searches, or video generation.',
     'وب‌سایت چه کارهایی را نمی‌تواند انجام دهد؟', 'وب‌سایت نمی‌تواند عملیات مستندن‌شده‌ای مانند ارسال ایمیل، انتشار در LinkedIn، معامله رمزارز، پرداخت، تراکنش کیف پول، جستجوی خارجی وب یا تولید ویدیو را انجام دهد.'),
)


FAQ_SEEDS = tuple(
    row
    for key, priority, en_keywords, fa_keywords, en_q, en_a, fa_q, fa_a in _PAIRS
    for row in (
        {
            'managedKey': f'{key}:en', 'question': en_q, 'aliases': [],
            'keywords': list(en_keywords), 'answer': en_a, 'language': 'en',
            'priority': priority,
        },
        {
            'managedKey': f'{key}:fa', 'question': fa_q, 'aliases': [],
            'keywords': list(fa_keywords), 'answer': fa_a, 'language': 'fa',
            'priority': priority,
        },
    )
)
